### ISSUE TITLE
Not quite sure on the instructions

### ISSUE THREAD

**Issue by cukiyoko** [RobbinBaauw/FloorplannerParser#2]
Hello Robbin,

Thank you so much for this script. I am having a bit of trouble making it work, can you help me?

I have installed Node and Yarn.
I unzipped the files I downloaded from here into a new folder: "FloorplannerParser-master", which contains the fmlparser.ts and package.json file.

From this folder, I run a cmd window with the command "yarn"
A new folder is created called "node_modules"

Now, this is where I get stuck.

Do I create the sources folder in the FloorplannerParser-master folder, or within the node_modules folder.
And where do I run the ts code from?

At the moment, I'm getting this error:

E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\fmlparser.ts:184
        for (const line of lines) {
                           ^
TypeError: Cannot read property 'length' of undefined
    at Function.Cuboid.parseCuboid (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\fmlparser.ts:184:28)
    at E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\fmlparser.ts:12:36
    at Parser.<anonymous> (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\xml2js\lib\parser.js:303:18)
    at Parser.emit (events.js:315:20)
    at Parser.EventEmitter.emit (domain.js:467:12)
    at SAXParser.onclosetag (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\xml2js\lib\parser.js:261:26)
    at emit (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\sax\lib\sax.js:624:35)
    at emitNode (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\sax\lib\sax.js:629:5)
    at closeTag (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master\node_modules\sax\lib\sax.js:1436:13)

E:\New\Downloads\FloorplannerParser-master\FloorplannerParser-master>

Could you please tell me where I'm going wrong?
Perhaps, if you could write me some instructions that are really easy to follow? I.e for someone who is not used to coding or using command prompt. So if you could tell me where to put the folder and where to put the code. Thank you!

**Comment by RobbinBaauw** [comment]
You should create a `sources` folder at the root of the directory `FloorplannerParser-master`, so in the end you have a file `FloorplannerParser-master/sources/house.fml`. Then you should also run `ts-node` from this directory (i.e. the root).

(note that this program may not work depending on the house you are dealing with, it's very limited)

**Comment by cukiyoko** [comment]
Hi, thanks so much for your help. Great, I did place the sources folder in the correct place (root), but I'm still getting an error message.

After yarn has made the node_modules folder, I open up a new command window in the root folder and put in: 

ts-node fmlparser.ts / tsc

then, depending, I either get: 

TypeError: Cannot read property 'length' of undefined 

or 

TypeError: Cannot read property 'project' of undefined

I just made a very simple fml file to test with - you can download it here:
https://drive.google.com/file/d/1o5Xd5Tilh_Cxa0tAYdx9BFkU26nh6hf5/view?usp=sharing

Can you please test it out and see what might be going wrong for me? Thanks so much again :)

**Comment by cukiyoko** [comment]
Hi again Robbin!

I've got the code working at last, but the Obj files it is producing don't seem right at all.
See the image below - it shows a really quick test I did, making a room with a few objects inside it in floorplanner.
You can see in this jpg that the object the code created is nothing like it - https://photos.app.goo.gl/trkbJPA5H9QcE8Mx9
Do you have any idea why it might not be working? In particular, I really need the actual furniture - chairs/tables ect.
Thanks so much for your help!
